[general]
import = [
  "/usr/lib/node_modules/alacritty-themes/themes/Gruvbox-Dark.toml"
]

[window]
opacity = 1
decorations = "Full"
decorations_theme_variant = "Dark"

[font]
size = 10

  [font.normal]
  family = "SauceCodeProNerdFontMono"

  [font.bold]
  family = "SauceCodeProNerdFontMono"

  [font.italic]
  family = "SauceCodeProNerdFontMono"

  [font.bold_italic]
  family = "SauceCodeProNerdFontMono"
